apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: chat-app
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

