apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: chat-app
spec:
  type: NodePort
  selector:
    app: mongodb-selec
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30017
