apiVersion: v1
kind: ServiceAccount
metadata:
  name: vulnerable-service-account
  namespace: chat-app


---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vulnerable-role
  namespace: chat-app
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vulnerable-role-binding
  namespace: chat-app
subjects:
- kind: ServiceAccount
  name: default
  namespace: chat-app
roleRef:
  kind: Role
  name: vulnerable-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vulnerable-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vulnerable-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: chat-app
roleRef:
  kind: ClusterRole
  name: vulnerable-cluster-role
  apiGroup: rbac.authorization.k8s.io

